name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag devenv:latest
      
    - name: Push image to DockerHub
      run: |
        docker login -u lixinyang -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker tag devenv:latest lixinyang/devenv:latest
        docker push lixinyang/devenv:latest
        docker logout
        
    - name: Push image to aliyun
      run: |
        docker login -u=lllxy啊啊啊 -p ${{ secrets.DOCKERHUB_PASSWORD }} registry.cn-shenzhen.aliyuncs.com
        docker tag devenv:latest registry.cn-shenzhen.aliyuncs.com/lllxy/devenv:latest
        docker push registry.cn-shenzhen.aliyuncs.com/lllxy/devenv:latest
